// @ts-check
// command: regenerate docs/known-gaps.md's own index of open sections from its headings
/**
 * `docs/known-gaps.md` sends every agent there to check what this project cannot do "before claiming a
 * thing is finished" — the moment they are least likely to read 450 lines of closed history first. 31 of
 * its 48 sections are already closed (DONE/CLOSED/STALE/MOVED/WRONG/RESOLVED/REFUTED in the heading), and
 * the thirteen that would actually stop somebody sit behind them with nothing pointing a reader there.
 *
 * The closed sections stay — deleting them would destroy the record of what was believed and what refuted
 * it, which is the whole point of the file. The defect is the ORDER and the missing index, not the content.
 *
 * DERIVED, never hand-written: a hand-maintained index is the fact-stated-twice shape this repo keeps
 * paying for. This reads the headings' own closed/open convention rather than restating it, so a section
 * closed without updating the index is a MISMATCH `known-gaps-index.test.ts` catches, not a silent drift.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { join } from "node:path";
import { refuseUnknownFlags } from "@a11ign/screenreader-fleet/cli-flags";

export const KNOWN_GAPS_FILE = "docs/known-gaps.md";

/** The same words a heading already uses to mark itself closed — see the file's own convention. */
export const CLOSED_PATTERN = /DONE|CLOSED|STALE|MOVED|WRONG|RESOLVED|REFUTED/;

export const INDEX_START = "<!-- known-gaps-index:start -->";
export const INDEX_END = "<!-- known-gaps-index:end -->";

/** @typedef {{ lineNumber: number, raw: string, number: number | null, title: string }} Heading */
/** @typedef {Heading & { anchor: string }} AnchoredHeading */

/**
 * Every `## ` heading in the file, in order. A heading with no leading "N. " is a META section (the
 * ordering note, the pattern note) rather than a numbered gap, and is never a candidate for the index.
 * @param {string} text
 */
export function parseHeadings(text: string) {
  /** @type {Heading[]} */
  const headings: Heading[] = [];
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const match = /^## (.*)$/.exec(lines[i]);
    if (!match) continue;
    const raw = match[1];
    const numbered = /^(\d+)\.\s*/.exec(raw);
    headings.push({
      lineNumber: i + 1,
      raw,
      number: numbered ? Number(numbered[1]) : null,
      title: numbered ? raw.slice(numbered[0].length) : raw,
    });
  }
  return headings;
}

/** @param {Heading} heading */
export function isClosed(heading: Heading) {
  return CLOSED_PATTERN.test(heading.raw);
}

/**
 * Approximates GitHub's own heading-anchor algorithm: strip markdown markup, lowercase, drop punctuation,
 * turn runs of whitespace into single hyphens, and disambiguate repeats the same way GitHub does (`-1`,
 * `-2`, ...). Good enough for a reader to click through; this is a navigation aid, not re-implementing
 * GitHub's renderer, so it is not asserted against GitHub's own output anywhere.
 * @param {string} raw
 */
export function slugify(raw: string) {
  const stripped = raw
    .replace(/~~/g, "")
    .replace(/\*\*/g, "")
    .replace(/`/g, "")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  return stripped
    .toLowerCase()
    .replace(/[^\w\- ]+/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

/**
 * Anchors are assigned across ALL headings in document order, because that is the scope GitHub
 * disambiguates within — an open section's anchor can be shifted by an unrelated closed one sharing its
 * slug.
 * @param {Heading[]} headings
 */
function withAnchors(headings: Heading[]) {
  /** @type {Map<string, number>} */
  const seen: Map<string, number> = new Map();
  return headings.map((heading) => {
    const slug = slugify(heading.raw);
    const count = seen.get(slug) ?? 0;
    seen.set(slug, count + 1);
    return { ...heading, anchor: count === 0 ? slug : `${slug}-${count}` };
  });
}

/** @param {string} text */
export function openSections(text: string) {
  return withAnchors(parseHeadings(text)).filter((h) => h.number !== null && !isClosed(h));
}

/** @param {string} title */
function cleanTitle(title: string) {
  return title.replace(/~~/g, "").replace(/\*\*/g, "").replace(/`/g, "").trim();
}

/** @param {string} text */
export function buildIndexBlock(text: string) {
  const open = openSections(text);
  const lines = [
    INDEX_START,
    "**Open sections** (generated by `scripts/known-gaps-index.ts` -- do not hand-edit; run "
      + "`pnpm run docs:known-gaps-index --write` after any section's heading changes):",
    ...open.map((h) => `- [§${h.number}](#${h.anchor}) ${cleanTitle(h.title)}`),
    INDEX_END,
  ];
  return lines.join("\n");
}

/** @param {string} text */
export function currentIndexBlock(text: string) {
  const start = text.indexOf(INDEX_START);
  const end = text.indexOf(INDEX_END);
  if (start === -1 || end === -1) return null;
  return text.slice(start, end + INDEX_END.length);
}

/**
 * Replaces an existing index block in place, or inserts a fresh one before the file's first heading.
 * @param {string} text
 */
export function applyIndexBlock(text: string) {
  const block = buildIndexBlock(text);
  const existing = currentIndexBlock(text);
  if (existing !== null) return text.replace(existing, block);
  const firstHeading = text.indexOf("\n## ");
  if (firstHeading === -1) throw new Error("known-gaps.md has no '## ' heading to insert the index before");
  return `${text.slice(0, firstHeading)}\n${block}\n${text.slice(firstHeading)}`;
}

function main() {
  // Guarded per #164: reads --write.
  refuseUnknownFlags(["--write"], { entry: import.meta.url, command: "node scripts/known-gaps-index.ts" });
  const repoRoot = fileURLToPath(new URL("../", import.meta.url));
  const path = join(repoRoot, KNOWN_GAPS_FILE);
  if (!existsSync(path)) {
    console.error(`${KNOWN_GAPS_FILE} does not exist`);
    process.exit(1);
  }
  const text = readFileSync(path, "utf8");
  const desired = applyIndexBlock(text);
  if (text === desired) {
    console.log(`OK  ${KNOWN_GAPS_FILE}'s index is current.`);
    return;
  }
  if (process.argv.includes("--write")) {
    writeFileSync(path, desired);
    console.log(`WROTE  ${KNOWN_GAPS_FILE}'s index regenerated.`);
    return;
  }
  console.error(`STALE  ${KNOWN_GAPS_FILE}'s index does not match its headings. `
    + "Run: pnpm run docs:known-gaps-index --write");
  process.exitCode = 1;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) main();
