/**
 * `docs/coverage.md` is GENERATED and DELIBERATELY UNTRACKED — issue #158, ceo-ruled 2026-09-07:
 * "Generated files, docs/coverage.md first, are regenerated and checked in CI, never committed in a PR."
 *
 * It used to be committed, and `git log` already showed it moving under commits whose subject was a
 * criterion change rather than a docs change — two branches that each touch a criterion both regenerate
 * this page, both commit their own correct-for-their-own-tree snapshot, and the second to land conflicts
 * with the first in a file neither author wrote a line of. Untracking removes the conflict outright: there
 * is no committed copy for two branches to disagree about.
 *
 * The cost, paid deliberately: a stranger can no longer click `docs/coverage.md` on GitHub and read it.
 * README.md and docs/README.md say so and name `npm run docs:coverage` as how to get it.
 *
 * So this file can no longer diff a fresh regeneration against a committed copy — there isn't one. What it
 * checks instead is SHAPE: the generator runs without throwing, the page says what it is, and it produced
 * something rather than nothing. That is not hypothetical here — `screenreader-coverage.md`'s own header
 * says "a behaviour missing from that table is not a missing feature; it is a claim this project cannot
 * currently make", and an empty or crashing generator is the sharpest version of that.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";
import { npmCliInvocation } from "../../../scripts/npm-cli-executable.ts";

const REPO = resolve(import.meta.dirname, "../../..");
const PAGE = resolve(REPO, "docs/coverage.md");

/** Regenerated fresh for every test in this file, never read as a leftover from a previous run or from a
 *  contributor's own working tree — the whole point of untracking is that nothing here trusts a copy
 *  already on disk. */
function regenerate(): string {
  const npx = npmCliInvocation("npx", ["tsx", "packages/lab/scripts/generate-coverage-doc.ts"]);
  execFileSync(npx.command, npx.args, { cwd: REPO, encoding: "utf8", stdio: "pipe" });
  return readFileSync(PAGE, "utf8");
}

test("the generator runs and marks its output as generated", () => {
  const page = regenerate();
  assert.match(page, /GENERATED by `npm run docs:coverage`/,
    "the page must say it is generated, or somebody will edit the local copy by hand and lose the edit "
    + "on the next run");
});

test("the page states a count, and the count is not zero", () => {
  // The vacuity guard. A generator that silently produced an empty table would pass the test above, since
  // it only checks the page SAYS it is generated, not that it generated anything real.
  const page = regenerate();
  const assessed = /\*\*assessed\*\* \| (\d+) \|/.exec(page);
  assert.ok(assessed && Number(assessed[1]) > 0, "the page claims zero assessed criteria");
  assert.ok(page.split("\n").filter((l) => l.startsWith("| **")).length >= 10,
    "fewer than ten criterion rows — the generator produced almost nothing");
});
